### Test the Azure Function with Markdown Content

# @rootUrl = https://markdown-to-form.azurewebsites.net
@rootUrl = http://localhost:7071
@markdownFile = ./UserSurvey.md

### Generate Form Template
POST {{rootUrl}}/api/MarkdownToSurvey HTTP/1.1
Content-Type: application/json

< ./UserSurvey.md

### Create and Publish Microsoft Form
POST {{rootUrl}}/api/MarkdownToSurvey HTTP/1.1
Content-Type: application/json

{
    "markdown": "< ./UserSurvey.md",
    "createForm": true
}
