### Test the Azure Function with Markdown Content

# @rootUrl = https://markdown-to-form.azurewebsites.net
@rootUrl = http://localhost:7071
@markdownFile = ./UserSurvey.md

### Send Markdown to Function
POST {{rootUrl}}/api/MarkdownToSurvey HTTP/1.1
Content-Type: application/json

< ./UserSurvey.md
